#!/bin/bash

function sigterm_handler() {
    echo "SIGTERM signal received, try to gracefully shutdown all services..."
    service apache2 stop
    service mysql stop
}

trap "sigterm_handler; exit" TERM

function entrypoint() {
    /usr/bin/mysqld_safe > /dev/null 2>&1 &
    service apache2 start
    wait
}

entrypoint
