#!/bin/bash

function sigterm_handler() {
    echo "SIGTERM signal received, try to gracefully shutdown all services..."
    service apache2 stop
    service mysql stop
}

trap "sigterm_handler; exit" TERM

function entrypoint() {
    service mysql start &
    service apache2 start &
    wait
}

entrypoint
